version: "3.9"
services:
  beszel:
    image: ghcr.io/beszel/beszel:latest
    container_name: beszel
    restart: unless-stopped
    env_file:
      - monitoring.env
    ports:
      - "8082:8080" # Changed to 8082 to avoid conflict with UniFi and WordPress
    environment:
      - BESZEL_DB_HOST=postgres_main
      - BESZEL_DB_USER=${BESZEL_DB_USER}
      - BESZEL_DB_PASSWORD=${BESZEL_DB_PASSWORD}
      - BESZEL_DB_NAME=beszel
      - BESZEL_DB_PORT=5432
    networks:
      - monitor_net

networks:
  monitor_net:
    external: true # Connects to the network created by the main stack
