version: "3.9"

services:
  beszel:
    image: henrygd/beszel
    container_name: beszel
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - beszel_data:/beszel_data
    networks:
      - monitor_net

volumes:
  beszel_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=$NFS_IP,nolock,soft,rw,nfsvers=4
      device: :/volume5/docker/beszel

networks:
  monitor_net:
    external: true # Connects to the network created by the main stack
