version: '2'
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=$API-KEY
      - ZONE=chinkes.com
      - SUBDOMAIN=home
      - PROXIED=false
      - CRON="@daily"
