version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "8053:53/tcp"
      - "8053:53/udp"
      #- "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "8081:80/tcp"
    environment:
      TZ: 'America/Denver'
      WEBPASSWORD: $PIPWD #'set a secure password here or it will be random'
      VIRTUAL_HOST: pi.chinkes.huis
      DNSMASQ_LISTENING: all
    # Volumes store your data between container upgrades
    volumes:
      - 'piholeNFS:/etc/pihole'
      - 'piholeNFS:/etc/dnsmasq.d'
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    #cap_add:
      # NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
    labels:
      # This label will prevent Watchtower from updating pihole
      # https://github.com/pi-hole/docker-pi-hole#note-on-watchtower
      - "com.centurylinklabs.watchtower.enable=false"
volumes:
  piholeNFS:
    driver: local
    driver_opts:
      type: nfs
      o: addr=$NFS_IP,nolock,soft,rw,nfsvers=4
      device: :/volume5/docker/wordpress-containers/pihole

# add lists to gravity from https://firebog.net/