version: "3.7"
services:
  controller:
    image: "jacobalberty/unifi:${TAG:-latest}"
    container_name: "${COMPOSE_PROJECT_NAME:-unifi}_controller"
    init: true
    restart: always
    volumes:
      - unifi-data:/unifi
    labels:
      # This label will prevent Watchtower from updating the controller automatically
      - "com.centurylinklabs.watchtower.enable=false"
    environment:
      - "TZ=America/Denver" # Set your timezone
      - "PUID=$PUID" # Optional: Set to your user ID
      - "PGID=$PGID" # Optional: Set to your group ID
      - "UNIFI_DB_HOST=127.0.0.1" # Force use of internal database
      - "SYSTEM_IP=$SYSTEM_IP" # Optional: Set to the IP of your host machine to help with discovery
    ports:
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8080:8080/tcp" # Device/ controller comm.
      - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
      - "8880:8880/tcp" # HTTP portal redirection
      - "8843:8843/tcp" # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery
      - "5514:5514/udp" # Remote syslog capture
    networks:
      - unifi

volumes:
  unifi-data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=$NFS_IP,nolock,soft,rw,nfsvers=4
      device: :/volume5/docker/unifi # Point to the parent directory for UniFi data

networks:
  unifi:
    name: unifi
