version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - wordpressNFS-mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - ${myPHPport}:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Pa$$w0rd 

  wordpress:
    depends_on: 
      - db
    image: wordpress:latest
    volumes:
      - wordpressNFS-wordpress:/var/www/html
    ports:
      - ${wpPort}:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      HTTP_X_FORWARDED_PROTO: true
       
volumes:
    wordpressNFS-mysql:
      driver: local
      driver_opts:
        type: nfs
        o: o: "addr=x.x.x.x,nolock,soft,rw"
        device: ":/volume5/docker/wordpress-containers/mysql/wp-1"

    wordpressNFS-wordpress:
      driver: local
      driver_opts:
        type: nfs
        o: o: "addr=x.x.x.x,nolock,soft,rw"
        device: ":/volume5/docker/wordpress-containers/wordpress/wp-1"
