version: '3'

services:
  db:
    #image: mariadb
    image: mysql:5.7
    # https://stackoverflow.com/questions/37644118/initializing-mysql-directory-error
    command: [--ignore-db-dir=lost+found]
    volumes:
      - wordpressNFS-mysql:/var/lib/mysql
    restart: always
    env_file:
      - stack.env

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - $MYPHP_PORT:80
    env_file:
      - stack.env 

  wordpress:
    depends_on: 
      - db
    image: wordpress:latest
    volumes:
      - wordpressNFS-wordpress:/var/www/html
    ports:
      - $WP_PORT:80
    restart: always
    env_file:
      - stack.env
       
volumes:
    wordpressNFS-mysql:
      driver: local
      driver_opts:
        type: nfs
        o: addr=$NFS_IP,nolock,soft,rw,nfsvers=4
        device: :/volume5/docker/wordpress-containers/$NFS_FOLDER/mysql

    wordpressNFS-wordpress:
      driver: local
      driver_opts:
        type: nfs
        o: addr=$NFS_IP,nolock,soft,rw,nfsvers=4
        device: :/volume5/docker/wordpress-containers/$NFS_FOLDER/wordpress