version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - wordpressNFS-mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "&2KCS749#mL#L8ytYOeg4D"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "&2KCS749#mL#L8ytYOeg4D" 

  wordpress:
    depends_on: 
      - db
    image: wordpress:latest
    volumes:
      - wordpressNFS-wordpress:/var/www/html
    ports:
      - 8080:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      HTTP_X_FORWARDED_PROTO: true
       
volumes:
    wordpressNFS-mysql:
      driver: local
      driver_opts:
        type: nfs
        o: rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14
        device: ":/volume5/docker/wordpress-containers/mysql/wp-1"

    wordpressNFS-wordpress:
      driver: local
      driver_opts:
        type: nfs
        o: rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14
        device: ":/volume5/docker/wordpress-containers/wordpress/wp-1"
